version: '3'

services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - react-client
    environment:
      DATABASE_URL: 'mongodb://mongo:27017/mydatabase?authSource=admin&directConnection=true'
  mongo:
    container_name: mongo
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
  react-client:
    build: ../react-client-app
    ports:
      - '80:80'
